import {run} from 'madrun';

export default {
    'start': () => 'bin/deepword.js package.json',
    'start:dev': () => 'NODE_ENV=development npm start',
    'test': () => 'tape \'{client,common,server}/**/*.spec.js\'',
    'coverage': () => 'nyc npm test',
    'report': () => 'nyc report --reporter=text-lcov | coveralls',
    'watcher:test': () => 'nodemon -e spec.js -w client -w server -w common -x ',
    'fix:lint': () => run('lint', '--fix'),
    'lint': () => 'putout .',
    'fresh:lint': () => run('lint', '--fresh'),
    'lint:fresh': () => run('lint', '--fresh'),
    'wisdom': () => run('build'),
    'build': () => run(['clean', 'mkdir', 'build:client*', 'cp:*']),
    'cp:socket.io:dist': () => 'cp node_modules/socket.io-client/dist/socket.io.js dist/socket.io.js',
    'cp:socket.io:dist-dev': () => 'cp node_modules/socket.io-client/dist/socket.io.js dist-dev/socket.io.js',
    'cp:socket.io.map:dist': () => 'cp node_modules/socket.io-client/dist/socket.io.js.map dist/socket.io.js.map',
    'cp:socket.io.map:dist-dev': () => 'cp node_modules/socket.io-client/dist/socket.io.js.map dist-dev/socket.io.js.map',
    'build-progress': () => 'webpack --progress',
    'build:client': () => run('build-progress', '--mode production'),
    'build:start': () => run(['build:client', 'start']),
    'build:client:dev': async () => `NODE_ENV=development ${await run('build-progress')} --mode development`,
    'build:start:dev': () => run(['build:client:dev', 'start:dev']),
    'watch:client': async () => `nodemon -w client -x "${await run('build:client')}"`,
    'watch:client:dev': async () => `NODE_ENV=development "${await run('watch:client')}"`,
    'mkdir': () => 'mkdirp dist dist-dev',
    'clean': () => 'rimraf dist dist-dev',
};

